// User action types
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";

// Category action types
export const FETCH_ALL_CATEGORIES_SUCCESS = "FETCH_ALL_CATEGORIES_SUCCESS";

// Topic action types
export const FETCH_TOPIC_SUCCESS = "FETCH_TOPIC_SUCCESS";
export const FETCH_TOPICS_SUCCESS = "FETCH_TOPICS_SUCCESS";
export const CREATE_TOPIC_POST_SUCCESS = "CREATE_TOPIC_POST_SUCCESS";
export const CREATE_POST_REPLY_SUCCESS = "CREATE_POST_REPLY_SUCCESS";

// Notification types
export const FETCH_UNREAD_NOTIFICATIONS_SUCCESS = "FETCH_UNREAD_NOTIFICATIONS_SUCCESS";
export const MARK_NOTIFICATION_SUCCESS = "MARK_NOTIFICATION_SUCCESS";
