// User action types
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";

// Category action types
export const FETCH_ALL_CATEGORIES_SUCCESS = "FETCH_ALL_CATEGORIES_SUCCESS";

// Topic action types
export const FETCH_TOPIC_SUCCESS = "FETCH_TOPIC_SUCCESS";
export const FETCH_LATEST_TOPICS_SUCCESS = "FETCH_LATEST_TOPICS_SUCCESS";
export const CREATE_TOPIC_POST_SUCCESS = "CREATE_TOPIC_POST_SUCCESS";
